package dev.lumina.project;

import java.io.ByteArrayInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.function.Consumer;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Creates new projects on disk.
 * JAVA        -> generated locally (Maven or Gradle layout + Main class).
 * SPRING_BOOT -> downloaded from start.spring.io (same service IntelliJ uses).
 * MAVEN_ARCHETYPE -> generated by the local Maven installation.
 * RUST        -> generated by Cargo or cargo-generate.
 */
public final class ProjectGenerator {

    private ProjectGenerator() {
    }

    /** Runs on a background thread; log lines go to the console. */
    public static Path generate(ProjectSpec spec, Consumer<String> log) throws IOException {
        Path dir = spec.projectDir();
        if ((spec.generator() == ProjectSpec.Generator.MAVEN_ARCHETYPE
                || spec.generator() == ProjectSpec.Generator.RUST) && Files.exists(dir)) {
            throw new IOException("Project directory already exists: " + dir);
        }
        if (Files.isDirectory(dir)) {
            try (var entries = Files.list(dir)) {
                if (entries.findAny().isPresent()) {
                    throw new IOException("Directory is not empty: " + dir);
                }
            }
        }
        if (spec.generator() != ProjectSpec.Generator.MAVEN_ARCHETYPE
                && spec.generator() != ProjectSpec.Generator.RUST) {
            Files.createDirectories(dir);
        }

        switch (spec.generator()) {
            case JAVA, KOTLIN, GROOVY -> generateJava(spec, dir, log);
            case JAVAFX -> generateJavaFX(spec, dir, log);
            case EMPTY_PROJECT -> Files.createDirectories(dir);
            case ANGULAR_CLI, VITE, HTML, REACT, EXPRESS, VUE, NUXT -> generateWebStarter(spec, dir, log);
            case QUARKUS -> generateQuarkus(spec, dir, log);
            case MICRONAUT, JAKARTA_EE, KTOR -> generateJava(spec, dir, log);
            case SPRING_BOOT -> generateSpringBoot(spec, dir, log);
            case MAVEN_ARCHETYPE -> generateMavenArchetype(spec, dir, log);
            case RUST -> generateRust(spec, dir, log);
        }

        if (spec.initGit()) {
            initGit(dir, log);
        }
        log.accept("\u2713 Project created at " + dir);
        return dir;
    }

    /** A small offline starter for the web generators when their CLIs are unavailable. */
    private static void generateWebStarter(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        log.accept("Generating " + spec.generator().name().toLowerCase().replace('_', ' ') + " project …");
        Files.writeString(dir.resolve("package.json"), """
                {
                  "name": "%s",
                  "private": true,
                  "version": "0.0.0",
                  "scripts": { "start": "echo 'Install dependencies to start this project'" }
                }
                """.formatted(spec.artifact()));
        Files.writeString(dir.resolve("README.md"), "# " + spec.name() + "\n\nCreated with Lumina IDE.\n");
    }

    // ------------------------------------------------------------ plain java

    private static void generateJava(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        log.accept("Generating Java project (" + spec.buildSystem() + ") \u2026");

        String pkg = spec.packageName();
        Path srcMain = dir.resolve("src/main/java");
        Path pkgDir = pkg.isBlank() ? srcMain : srcMain.resolve(pkg.replace('.', '/'));
        Files.createDirectories(pkgDir);
        Files.createDirectories(dir.resolve("src/main/resources"));
        Files.createDirectories(dir.resolve("src/test/java"));

        String pkgLine = pkg.isBlank() ? "" : "package " + pkg + ";\n\n";
        Files.writeString(pkgDir.resolve("Main.java"), pkgLine + """
                public class Main {
                    public static void main(String[] args) {
                        System.out.println("Hello from %s!");
                    }
                }
                """.formatted(spec.name()));

        if (spec.buildSystem() == ProjectSpec.BuildSystem.MAVEN) {
            Files.writeString(dir.resolve("pom.xml"), """
                    <?xml version="1.0" encoding="UTF-8"?>
                    <project xmlns="http://maven.apache.org/POM/4.0.0"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                        <modelVersion>4.0.0</modelVersion>
                        <groupId>%s</groupId>
                        <artifactId>%s</artifactId>
                        <version>1.0-SNAPSHOT</version>
                        <properties>
                            <maven.compiler.release>%s</maven.compiler.release>
                            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                        </properties>
                        <dependencies>
                            <dependency>
                                <groupId>org.junit.jupiter</groupId>
                                <artifactId>junit-jupiter</artifactId>
                                <version>5.10.2</version>
                                <scope>test</scope>
                            </dependency>
                        </dependencies>
                        <build>
                            <plugins>
                                <plugin>
                                    <groupId>org.apache.maven.plugins</groupId>
                                    <artifactId>maven-surefire-plugin</artifactId>
                                    <version>3.2.5</version>
                                </plugin>
                            </plugins>
                        </build>
                    </project>
                    """.formatted(spec.group(), spec.artifact(), spec.javaVersion()));
        } else {
            Files.writeString(dir.resolve("settings.gradle"),
                    "rootProject.name = '" + spec.artifact() + "'\n");
            Files.writeString(dir.resolve("build.gradle"), """
                    plugins {
                        id 'java'
                        id 'application'
                    }

                    group = '%s'
                    version = '1.0-SNAPSHOT'

                    java {
                        toolchain {
                            languageVersion = JavaLanguageVersion.of(%s)
                        }
                    }

                    repositories {
                        mavenCentral()
                    }

                    dependencies {
                        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
                        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
                    }

                    test {
                        useJUnitPlatform()
                    }

                    application {
                        mainClass = '%s'
                    }
                    """.formatted(spec.group(), spec.javaVersion(),
                    pkg.isBlank() ? "Main" : pkg + ".Main"));
        }

        Files.writeString(dir.resolve(".gitignore"), """
                target/
                build/
                .gradle/
                .idea/
                .lumina/
                *.class
                *.log
                """);
        Files.writeString(dir.resolve("README.md"),
                "# " + spec.name() + "\n\nCreated with Lumina IDE.\n");
    }

    // ---------------------------------------------------------------- javafx

    private static void generateJavaFX(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        log.accept("Generating JavaFX project (" + spec.buildSystem() + ", " + spec.language() + ") \u2026");

        String pkg = spec.packageName();
        if (pkg == null || pkg.isBlank()) {
            String g = spec.group() == null || spec.group().isBlank() ? "com.example" : spec.group();
            String a = spec.artifact() == null || spec.artifact().isBlank() ? "demo"
                    : spec.artifact().toLowerCase().replaceAll("[^a-z0-9_]", "");
            pkg = (g + "." + a).replaceAll("^\\.+|\\.+$", "");
        }
        String pkgPath = pkg.replace('.', '/');

        Path srcMain = dir.resolve("src/main");
        Path srcMainJava = srcMain.resolve("java");
        Path srcMainResources = srcMain.resolve("resources");
        Path pkgJavaDir = srcMainJava.resolve(pkgPath);
        Path pkgResDir = srcMainResources.resolve(pkgPath);
        Files.createDirectories(pkgJavaDir);
        Files.createDirectories(pkgResDir);
        Files.createDirectories(dir.resolve("src/test/java"));

        java.util.Set<String> selectedLibs = new java.util.LinkedHashSet<>();
        if (spec.javafxDependencies() != null && !spec.javafxDependencies().isBlank()) {
            for (String dep : spec.javafxDependencies().split(",")) {
                String trimmed = dep.trim().toLowerCase();
                if (!trimmed.isEmpty()) selectedLibs.add(trimmed);
            }
        }

        String javaVersion = spec.javaVersion() != null && !spec.javaVersion().isBlank()
                ? spec.javaVersion() : "21";
        String javafxVersion = "23.0.2";

        // Build file generation (Maven or Gradle)
        if (spec.buildSystem() == ProjectSpec.BuildSystem.MAVEN) {
            StringBuilder mavenDeps = new StringBuilder();
            if (selectedLibs.contains("bootstrapfx")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>org.kordamp.bootstrapfx</groupId>
                                <artifactId>bootstrapfx-core</artifactId>
                                <version>0.4.0</version>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("controlsfx")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>org.controlsfx</groupId>
                                <artifactId>controlsfx</artifactId>
                                <version>11.2.1</version>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("formsfx")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>com.dlsc.formsfx</groupId>
                                <artifactId>formsfx-core</artifactId>
                                <version>11.6.0</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.openjfx</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("fxgl")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>com.github.almasb</groupId>
                                <artifactId>fxgl</artifactId>
                                <version>21.1</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.openjfx</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("ikonli")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>org.kordamp.ikonli</groupId>
                                <artifactId>ikonli-javafx</artifactId>
                                <version>12.3.1</version>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("tilesfx")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>eu.hansolo</groupId>
                                <artifactId>tilesfx</artifactId>
                                <version>21.0.9</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.openjfx</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                """);
            }
            if (selectedLibs.contains("validatorfx")) {
                mavenDeps.append("""
                            <dependency>
                                <groupId>net.synedra</groupId>
                                <artifactId>validatorfx</artifactId>
                                <version>0.6.1</version>
                                <exclusions>
                                    <exclusion>
                                        <groupId>org.openjfx</groupId>
                                        <artifactId>*</artifactId>
                                    </exclusion>
                                </exclusions>
                            </dependency>
                """);
            }

            Files.writeString(dir.resolve("pom.xml"), """
                    <?xml version="1.0" encoding="UTF-8"?>
                    <project xmlns="http://maven.apache.org/POM/4.0.0"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                        <modelVersion>4.0.0</modelVersion>
                    
                        <groupId>%s</groupId>
                        <artifactId>%s</artifactId>
                        <version>1.0-SNAPSHOT</version>
                        <name>%s</name>
                    
                        <properties>
                            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                            <junit.version>5.10.2</junit.version>
                            <javafx.version>%s</javafx.version>
                            <maven.compiler.release>%s</maven.compiler.release>
                        </properties>
                    
                        <dependencies>
                            <dependency>
                                <groupId>org.openjfx</groupId>
                                <artifactId>javafx-controls</artifactId>
                                <version>${javafx.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.openjfx</groupId>
                                <artifactId>javafx-fxml</artifactId>
                                <version>${javafx.version}</version>
                            </dependency>
                    %s
                            <dependency>
                                <groupId>org.junit.jupiter</groupId>
                                <artifactId>junit-jupiter-api</artifactId>
                                <version>${junit.version}</version>
                                <scope>test</scope>
                            </dependency>
                            <dependency>
                                <groupId>org.junit.jupiter</groupId>
                                <artifactId>junit-jupiter-engine</artifactId>
                                <version>${junit.version}</version>
                                <scope>test</scope>
                            </dependency>
                        </dependencies>
                    
                        <build>
                            <plugins>
                                <plugin>
                                    <groupId>org.apache.maven.plugins</groupId>
                                    <artifactId>maven-compiler-plugin</artifactId>
                                    <version>3.13.0</version>
                                    <configuration>
                                        <release>${maven.compiler.release}</release>
                                    </configuration>
                                </plugin>
                                <plugin>
                                    <groupId>org.openjfx</groupId>
                                    <artifactId>javafx-maven-plugin</artifactId>
                                    <version>0.0.8</version>
                                    <executions>
                                        <execution>
                                            <id>default-cli</id>
                                            <configuration>
                                                <mainClass>%s.HelloApplication</mainClass>
                                                <launcher>app</launcher>
                                            </configuration>
                                        </execution>
                                    </executions>
                                </plugin>
                            </plugins>
                        </build>
                    </project>
                    """.formatted(spec.group(), spec.artifact(), spec.name(),
                            javafxVersion, javaVersion, mavenDeps.toString(), pkg));
        } else {
            Files.writeString(dir.resolve("settings.gradle"),
                    "rootProject.name = '" + spec.artifact() + "'\n");

            StringBuilder gradleDeps = new StringBuilder();
            if (selectedLibs.contains("bootstrapfx")) {
                gradleDeps.append("    implementation('org.kordamp.bootstrapfx:bootstrapfx-core:0.4.0')\n");
            }
            if (selectedLibs.contains("controlsfx")) {
                gradleDeps.append("    implementation('org.controlsfx:controlsfx:11.2.1')\n");
            }
            if (selectedLibs.contains("formsfx")) {
                gradleDeps.append("    implementation('com.dlsc.formsfx:formsfx-core:11.6.0') { exclude(group: 'org.openjfx') }\n");
            }
            if (selectedLibs.contains("fxgl")) {
                gradleDeps.append("    implementation('com.github.almasb:fxgl:21.1') { exclude(group: 'org.openjfx') }\n");
            }
            if (selectedLibs.contains("ikonli")) {
                gradleDeps.append("    implementation('org.kordamp.ikonli:ikonli-javafx:12.3.1')\n");
            }
            if (selectedLibs.contains("tilesfx")) {
                gradleDeps.append("    implementation('eu.hansolo:tilesfx:21.0.9') { exclude(group: 'org.openjfx') }\n");
            }
            if (selectedLibs.contains("validatorfx")) {
                gradleDeps.append("    implementation('net.synedra:validatorfx:0.6.1') { exclude(group: 'org.openjfx') }\n");
            }

            Files.writeString(dir.resolve("build.gradle"), """
                    plugins {
                        id 'java'
                        id 'application'
                        id 'org.openjfx.javafxplugin' version '0.1.0'
                    }

                    group '%s'
                    version '1.0-SNAPSHOT'

                    repositories {
                        mavenCentral()
                    }

                    ext {
                        junitVersion = '5.10.2'
                    }

                    sourceCompatibility = '%s'
                    targetCompatibility = '%s'

                    tasks.withType(JavaCompile) {
                        options.encoding = 'UTF-8'
                    }

                    application {
                        mainModule = '%s'
                        mainClass = '%s.HelloApplication'
                    }

                    javafx {
                        version = '%s'
                        modules = ['javafx.controls', 'javafx.fxml']
                    }

                    dependencies {
                    %s
                        testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
                        testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
                    }

                    test {
                        useJUnitPlatform()
                    }
                    """.formatted(spec.group(), javaVersion, javaVersion,
                            pkg, pkg, javafxVersion, gradleDeps.toString()));
        }

        // module-info.java
        StringBuilder moduleRequires = new StringBuilder();
        if (selectedLibs.contains("bootstrapfx")) {
            moduleRequires.append("    requires org.kordamp.bootstrapfx.core;\n");
        }
        if (selectedLibs.contains("controlsfx")) {
            moduleRequires.append("    requires org.controlsfx.controls;\n");
        }
        if (selectedLibs.contains("formsfx")) {
            moduleRequires.append("    requires com.dlsc.formsfx.core;\n");
        }
        if (selectedLibs.contains("fxgl")) {
            moduleRequires.append("    requires com.almasb.fxgl.all;\n");
        }
        if (selectedLibs.contains("ikonli")) {
            moduleRequires.append("    requires org.kordamp.ikonli.javafx;\n");
        }
        if (selectedLibs.contains("tilesfx")) {
            moduleRequires.append("    requires eu.hansolo.tilesfx;\n");
        }
        if (selectedLibs.contains("validatorfx")) {
            moduleRequires.append("    requires net.synedra.validatorfx;\n");
        }

        Files.writeString(srcMainJava.resolve("module-info.java"), """
                module %s {
                    requires javafx.controls;
                    requires javafx.fxml;
                %s
                    opens %s to javafx.fxml;
                    exports %s;
                }
                """.formatted(pkg, moduleRequires.toString(), pkg, pkg));

        // Source code by language
        if (spec.language() == ProjectSpec.Language.KOTLIN) {
            Path kotlinDir = dir.resolve("src/main/kotlin").resolve(pkgPath);
            Files.createDirectories(kotlinDir);
            Files.writeString(kotlinDir.resolve("HelloApplication.kt"), """
                    package %s

                    import javafx.application.Application
                    import javafx.fxml.FXMLLoader
                    import javafx.scene.Scene
                    import javafx.stage.Stage

                    class HelloApplication : Application() {
                        override fun start(stage: Stage) {
                            val fxmlLoader = FXMLLoader(HelloApplication::class.java.getResource("hello-view.fxml"))
                            val scene = Scene(fxmlLoader.load(), 320.0, 240.0)
                            stage.title = "Hello!"
                            stage.scene = scene
                            stage.show()
                        }
                    }

                    fun main() {
                        Application.launch(HelloApplication::class.java)
                    }
                    """.formatted(pkg));

            Files.writeString(kotlinDir.resolve("HelloController.kt"), """
                    package %s

                    import javafx.fxml.FXML
                    import javafx.scene.control.Label

                    class HelloController {
                        @FXML
                        private lateinit var welcomeText: Label

                        @FXML
                        private fun onHelloButtonClick() {
                            welcomeText.text = "Welcome to JavaFX Application!"
                        }
                    }
                    """.formatted(pkg));
        } else if (spec.language() == ProjectSpec.Language.GROOVY) {
            Path groovyDir = dir.resolve("src/main/groovy").resolve(pkgPath);
            Files.createDirectories(groovyDir);
            Files.writeString(groovyDir.resolve("HelloApplication.groovy"), """
                    package %s

                    import javafx.application.Application
                    import javafx.fxml.FXMLLoader
                    import javafx.scene.Scene
                    import javafx.stage.Stage

                    class HelloApplication extends Application {
                        @Override
                        void start(Stage stage) {
                            FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("hello-view.fxml"))
                            Scene scene = new Scene(fxmlLoader.load(), 320, 240)
                            stage.title = "Hello!"
                            stage.scene = scene
                            stage.show()
                        }

                        static void main(String[] args) {
                            launch(args)
                        }
                    }
                    """.formatted(pkg));

            Files.writeString(groovyDir.resolve("HelloController.groovy"), """
                    package %s

                    import javafx.fxml.FXML
                    import javafx.scene.control.Label

                    class HelloController {
                        @FXML
                        private Label welcomeText

                        @FXML
                        void onHelloButtonClick() {
                            welcomeText.text = "Welcome to JavaFX Application!"
                        }
                    }
                    """.formatted(pkg));
        } else {
            // Standard Java
            Files.writeString(pkgJavaDir.resolve("HelloApplication.java"), """
                    package %s;

                    import javafx.application.Application;
                    import javafx.fxml.FXMLLoader;
                    import javafx.scene.Scene;
                    import javafx.stage.Stage;

                    import java.io.IOException;

                    public class HelloApplication extends Application {
                        @Override
                        public void start(Stage stage) throws IOException {
                            FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("hello-view.fxml"));
                            Scene scene = new Scene(fxmlLoader.load(), 320, 240);
                            stage.setTitle("Hello!");
                            stage.setScene(scene);
                            stage.show();
                        }

                        public static void main(String[] args) {
                            launch();
                        }
                    }
                    """.formatted(pkg));

            Files.writeString(pkgJavaDir.resolve("HelloController.java"), """
                    package %s;

                    import javafx.fxml.FXML;
                    import javafx.scene.control.Label;

                    public class HelloController {
                        @FXML
                        private Label welcomeText;

                        @FXML
                        protected void onHelloButtonClick() {
                            welcomeText.setText("Welcome to JavaFX Application!");
                        }
                    }
                    """.formatted(pkg));
        }

        // hello-view.fxml in resources
        Files.writeString(pkgResDir.resolve("hello-view.fxml"), """
                <?xml version="1.0" encoding="UTF-8"?>

                <?import javafx.geometry.Insets?>
                <?import javafx.scene.control.Label?>
                <?import javafx.scene.layout.VBox?>

                <?import javafx.scene.control.Button?>
                <VBox alignment="CENTER" spacing="20.0" xmlns:fx="http://javafx.com/fxml"
                      fx:controller="%s.HelloController">
                    <padding>
                        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0"/>
                    </padding>

                    <Label fx:id="welcomeText"/>
                    <Button text="Hello!" onAction="#onHelloButtonClick"/>
                </VBox>
                """.formatted(pkg));

        Files.writeString(dir.resolve(".gitignore"), """
                target/
                build/
                .gradle/
                .idea/
                .lumina/
                *.class
                *.log
                """);

        Files.writeString(dir.resolve("README.md"),
                "# " + spec.name() + "\n\nJavaFX application created with Lumina IDE.\n");
    }


    // ----------------------------------------------------------- spring boot

    private static void generateSpringBoot(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        String type = spec.buildSystem() == ProjectSpec.BuildSystem.MAVEN
                ? "maven-project" : "gradle-project";

        StringBuilder url = new StringBuilder("https://start.spring.io/starter.zip")
                .append("?type=").append(type)
                .append("&language=").append(enc(spec.language().name().toLowerCase()))
                .append("&packaging=").append(enc(spec.packaging().name().toLowerCase()))
                .append("&javaVersion=").append(enc(spec.javaVersion()))
                .append("&groupId=").append(enc(spec.group()))
                .append("&artifactId=").append(enc(spec.artifact()))
                .append("&name=").append(enc(spec.name()))
                .append("&packageName=").append(enc(spec.packageName()));
        String deps = spec.springDependencies() == null ? "" : spec.springDependencies()
                .replace(" ", "");
        if (!deps.isBlank()) {
            url.append("&dependencies=").append(enc(deps));
        }
        String bootVersion = spec.springBootVersion();
        if (bootVersion != null && !bootVersion.isBlank()) {
            url.append("&bootVersion=").append(enc(bootVersion));
        }

        log.accept("Requesting project from start.spring.io \u2026");

        HttpClient client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(15))
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build();
        HttpRequest request = HttpRequest.newBuilder(URI.create(url.toString()))
                .timeout(Duration.ofSeconds(60))
                .GET()
                .build();

        HttpResponse<byte[]> response;
        try {
            response = client.send(request, HttpResponse.BodyHandlers.ofByteArray());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException("Download interrupted", e);
        }
        if (response.statusCode() != 200) {
            String body = new String(response.body(), StandardCharsets.UTF_8);
            throw new IOException("start.spring.io returned HTTP " + response.statusCode()
                    + (body.isBlank() ? "" : "\n" + shorten(body)));
        }

        log.accept("Unpacking " + (response.body().length / 1024) + " KB \u2026");
        unzip(response.body(), dir);

        // ZipInputStream drops Unix permissions: restore the wrappers' exec bit.
        for (String wrapper : new String[]{"mvnw", "gradlew"}) {
            Path w = dir.resolve(wrapper);
            if (Files.isRegularFile(w) && !w.toFile().setExecutable(true)) {
                log.accept("Note: could not mark " + wrapper + " executable");
            }
        }
    }

    // ----------------------------------------------------------- quarkus

    private static void generateQuarkus(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        String base = QuarkusMetadata.normalizeServerUrl(spec.quarkusServerUrl());
        StringBuilder url = new StringBuilder(base).append("/api/download");
        String group = spec.group().isBlank() ? "org.example" : spec.group();
        String artifact = spec.artifact().isBlank() ? spec.name().toLowerCase().replaceAll("[^a-z0-9.\\-]", "") : spec.artifact();
        String buildTool = spec.quarkusBuildTool() != null && !spec.quarkusBuildTool().isBlank()
                ? spec.quarkusBuildTool() : "MAVEN";

        url.append("?g=").append(enc(group))
                .append("&a=").append(enc(artifact))
                .append("&v=").append(enc(spec.projectVersion().isBlank() ? "1.0.0-SNAPSHOT" : spec.projectVersion()))
                .append("&b=").append(enc(buildTool));

        if (spec.quarkusStream() != null && !spec.quarkusStream().isBlank()) {
            url.append("&s=").append(enc(spec.quarkusStream()));
        }
        if (!spec.addSampleCode()) {
            url.append("&noCode=true");
        }

        if (spec.quarkusExtensions() != null && !spec.quarkusExtensions().isBlank()) {
            for (String ext : spec.quarkusExtensions().split(",")) {
                String trimmed = ext.trim();
                if (!trimmed.isEmpty()) {
                    url.append("&e=").append(enc(trimmed));
                }
            }
        }
        if (spec.language() == ProjectSpec.Language.KOTLIN) {
            if (spec.quarkusExtensions() == null || !spec.quarkusExtensions().contains("quarkus-kotlin")) {
                url.append("&e=").append(enc("io.quarkus:quarkus-kotlin"));
            }
        }

        log.accept("Requesting Quarkus project from " + base + " …");

        boolean downloaded = false;
        try {
            HttpClient client = HttpClient.newBuilder()
                    .connectTimeout(Duration.ofSeconds(12))
                    .followRedirects(HttpClient.Redirect.NORMAL)
                    .build();
            HttpRequest request = HttpRequest.newBuilder(URI.create(url.toString()))
                    .timeout(Duration.ofSeconds(45))
                    .header("User-Agent", "Lumina-IDE")
                    .GET()
                    .build();

            HttpResponse<byte[]> response = client.send(request, HttpResponse.BodyHandlers.ofByteArray());
            if (response.statusCode() == 200 && response.body() != null && response.body().length > 0) {
                log.accept("Unpacking Quarkus project (" + (response.body().length / 1024) + " KB) …");
                unzip(response.body(), dir);
                for (String wrapper : new String[]{"mvnw", "gradlew"}) {
                    Path w = dir.resolve(wrapper);
                    if (Files.isRegularFile(w) && !w.toFile().setExecutable(true)) {
                        log.accept("Note: could not mark " + wrapper + " executable");
                    }
                }
                downloaded = true;
            } else {
                log.accept("Note: " + base + " returned HTTP " + response.statusCode() + " — using offline template.");
            }
        } catch (Exception e) {
            log.accept("Note: could not reach " + base + " (" + e.getMessage() + ") — using offline template.");
        }

        if (!downloaded) {
            generateLocalQuarkus(spec, dir, group, artifact, log);
        }
    }

    private static void generateLocalQuarkus(ProjectSpec spec, Path dir, String group, String artifact, Consumer<String> log)
            throws IOException {
        log.accept("Generating local Quarkus project …");
        String version = (spec.quarkusStream() != null && !spec.quarkusStream().isBlank())
                ? spec.quarkusStream() : "3.15.3";
        boolean isKotlin = spec.language() == ProjectSpec.Language.KOTLIN;
        boolean isGradle = "GRADLE".equalsIgnoreCase(spec.quarkusBuildTool())
                || "GRADLE_KOTLIN_DSL".equalsIgnoreCase(spec.quarkusBuildTool());

        Path srcMain = isKotlin ? dir.resolve("src/main/kotlin") : dir.resolve("src/main/java");
        String pkg = spec.packageName().isBlank() ? group : spec.packageName();
        Path pkgDir = pkg.isBlank() ? srcMain : srcMain.resolve(pkg.replace('.', '/'));
        Files.createDirectories(pkgDir);
        Files.createDirectories(dir.resolve("src/main/resources"));
        Files.createDirectories(dir.resolve("src/test/java"));

        // application.properties
        Files.writeString(dir.resolve("src/main/resources/application.properties"), """
                # Quarkus Application Configuration
                quarkus.application.name=%s
                quarkus.http.port=8080
                """.formatted(artifact));

        // Sample code
        if (spec.addSampleCode()) {
            if (isKotlin) {
                Files.writeString(pkgDir.resolve("GreetingResource.kt"), """
                        package %s

                        import jakarta.ws.rs.GET
                        import jakarta.ws.rs.Path
                        import jakarta.ws.rs.Produces
                        import jakarta.ws.rs.core.MediaType

                        @Path("/hello")
                        class GreetingResource {

                            @GET
                            @Produces(MediaType.TEXT_PLAIN)
                            fun hello() = "Hello from Quarkus REST"
                        }
                        """.formatted(pkg));
            } else {
                Files.writeString(pkgDir.resolve("GreetingResource.java"), """
                        package %s;

                        import jakarta.ws.rs.GET;
                        import jakarta.ws.rs.Path;
                        import jakarta.ws.rs.Produces;
                        import jakarta.ws.rs.core.MediaType;

                        @Path("/hello")
                        public class GreetingResource {

                            @GET
                            @Produces(MediaType.TEXT_PLAIN)
                            public String hello() {
                                return "Hello from Quarkus REST";
                            }
                        }
                        """.formatted(pkg));
            }
        }

        if (isGradle) {
            Files.writeString(dir.resolve("settings.gradle"), "rootProject.name = '" + artifact + "'\n");
            Files.writeString(dir.resolve("build.gradle"), """
                    plugins {
                        id 'java'
                        id 'io.quarkus' version '%s'
                    }

                    group '%s'
                    version '1.0.0-SNAPSHOT'

                    repositories {
                        mavenCentral()
                    }

                    dependencies {
                        implementation enforcedPlatform("io.quarkus.platform:quarkus-bom:%s")
                        implementation 'io.quarkus:quarkus-rest'
                        testImplementation 'io.quarkus:quarkus-junit5'
                        testImplementation 'io.rest-assured:rest-assured'
                    }
                    """.formatted(version, group, version));
        } else {
            // Maven pom.xml
            StringBuilder depsXml = new StringBuilder();
            depsXml.append("""
                            <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-rest</artifactId>
                            </dependency>
                    """);
            if (spec.quarkusExtensions() != null && !spec.quarkusExtensions().isBlank()) {
                for (String ext : spec.quarkusExtensions().split(",")) {
                    String trimmed = ext.trim();
                    if (!trimmed.isEmpty() && !trimmed.equals("io.quarkus:quarkus-rest")) {
                        int idx = trimmed.indexOf(':');
                        if (idx > 0) {
                            String g = trimmed.substring(0, idx);
                            String a = trimmed.substring(idx + 1);
                            depsXml.append("""
                                            <dependency>
                                                <groupId>%s</groupId>
                                                <artifactId>%s</artifactId>
                                            </dependency>
                                    """.formatted(g, a));
                        }
                    }
                }
            }

            Files.writeString(dir.resolve("pom.xml"), """
                    <?xml version="1.0" encoding="UTF-8"?>
                    <project xmlns="http://maven.apache.org/POM/4.0.0"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
                        <modelVersion>4.0.0</modelVersion>
                        <groupId>%s</groupId>
                        <artifactId>%s</artifactId>
                        <version>1.0.0-SNAPSHOT</version>

                        <properties>
                            <maven.compiler.release>%s</maven.compiler.release>
                            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                            <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                            <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
                            <quarkus.platform.version>%s</quarkus.platform.version>
                        </properties>

                        <dependencyManagement>
                            <dependencies>
                                <dependency>
                                    <groupId>${quarkus.platform.group-id}</groupId>
                                    <artifactId>${quarkus.platform.artifact-id}</artifactId>
                                    <version>${quarkus.platform.version}</version>
                                    <type>pom</type>
                                    <scope>import</scope>
                                </dependency>
                            </dependencies>
                        </dependencyManagement>

                        <dependencies>
                    %s        <dependency>
                                <groupId>io.quarkus</groupId>
                                <artifactId>quarkus-junit5</artifactId>
                                <scope>test</scope>
                            </dependency>
                            <dependency>
                                <groupId>io.rest-assured</groupId>
                                <artifactId>rest-assured</artifactId>
                                <scope>test</scope>
                            </dependency>
                        </dependencies>

                        <build>
                            <plugins>
                                <plugin>
                                    <groupId>io.quarkus.platform</groupId>
                                    <artifactId>quarkus-maven-plugin</artifactId>
                                    <version>${quarkus.platform.version}</version>
                                    <extensions>true</extensions>
                                    <executions>
                                        <execution>
                                            <goals>
                                                <goal>build</goal>
                                                <goal>generate-code</goal>
                                                <goal>generate-code-tests</goal>
                                            </goals>
                                        </execution>
                                    </executions>
                                </plugin>
                            </plugins>
                        </build>
                    </project>
                    """.formatted(group, artifact, spec.javaVersion().isBlank() ? "21" : spec.javaVersion(), version, depsXml.toString()));
        }
    }

    // -------------------------------------------------------- maven archetype

    private static void generateMavenArchetype(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        Files.createDirectories(spec.location());

        String archetype = required(spec.archetypeId(), "maven-archetype-quickstart");
        int separator = archetype.indexOf(':');
        String archetypeGroupId = separator > 0
                ? archetype.substring(0, separator) : "org.apache.maven.archetypes";
        String archetypeId = separator > 0 ? archetype.substring(separator + 1) : archetype;
        String archetypeVersion = required(spec.archetypeVersion(), "1.4");
        String projectVersion = required(spec.projectVersion(), "1.0-SNAPSHOT");
        String catalog = switch (required(spec.archetypeCatalog(), "Internal")) {
            case "Default Local" -> "local";
            case "Maven Central" -> "remote";
            default -> "internal";
        };

        log.accept("Generating Maven project from " + archetypeId + " …");
        ProcessBuilder builder = new ProcessBuilder(
                "mvn", "archetype:generate", "-B",
                "-DarchetypeCatalog=" + catalog,
                "-DarchetypeGroupId=" + archetypeGroupId,
                "-DarchetypeArtifactId=" + archetypeId,
                "-DarchetypeVersion=" + archetypeVersion,
                "-DgroupId=" + spec.group(),
                "-DartifactId=" + spec.artifact(),
                "-Dversion=" + projectVersion,
                "-Dpackage=" + spec.packageName())
                .directory(spec.location().toFile())
                .redirectErrorStream(true);
        addAdditionalProperties(builder, spec.additionalProperties());

        Process process = builder.start();
        try (BufferedReader output = new BufferedReader(new InputStreamReader(
                process.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = output.readLine()) != null) {
                log.accept(line);
            }
        }
        try {
            int exitCode = process.waitFor();
            if (exitCode != 0) {
                throw new IOException("Maven archetype generation failed with exit code " + exitCode);
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException("Maven archetype generation interrupted", e);
        }

        if (!Files.isDirectory(dir)) {
            throw new IOException("Maven did not create the expected project directory: " + dir);
        }
    }

    private static void addAdditionalProperties(ProcessBuilder builder, String properties) {
        if (properties == null || properties.isBlank()) {
            return;
        }
        for (String property : properties.split("[\\r\\n,]+")) {
            String trimmed = property.trim();
            if (!trimmed.isBlank() && trimmed.contains("=")) {
                builder.command().add("-D" + trimmed);
            }
        }
    }

    // ------------------------------------------------------------------ rust

    private static void generateRust(ProjectSpec spec, Path dir, Consumer<String> log)
            throws IOException {
        Files.createDirectories(spec.location());
        String cargo = cargoExecutable(spec.rustToolchainPath());
        String template = required(spec.rustTemplate(), "Binary (application)");
        List<String> command = new java.util.ArrayList<>();
        command.add(cargo);
        if (template.startsWith("Custom:")) {
            String url = template.substring("Custom:".length()).trim();
            if (url.isBlank()) throw new IOException("Custom Rust template URL is required");
            command.addAll(List.of("generate", "--git", url, "--name", spec.name()));
            log.accept("Generating Rust project from " + url + " …");
        } else {
            command.add("new");
            command.add(template.startsWith("Library") ? "--lib" : "--bin");
            command.add(spec.name());
            log.accept("Generating Rust " + (template.startsWith("Library") ? "library" : "binary")
                    + " with Cargo …");
        }

        ProcessBuilder builder = new ProcessBuilder(command)
                .directory(spec.location().toFile())
                .redirectErrorStream(true);
        addEnvironment(builder, spec.rustEnvironment());
        runProcess(builder, "Rust project generation", log);
        if (!Files.isDirectory(dir)) {
            throw new IOException("Cargo did not create the expected project directory: " + dir);
        }
    }

    private static String cargoExecutable(String toolchainPath) {
        if (toolchainPath == null || toolchainPath.isBlank()) return "cargo";
        Path candidate = Path.of(toolchainPath).resolve("cargo");
        return Files.isExecutable(candidate) ? candidate.toString() : "cargo";
    }

    private static void addEnvironment(ProcessBuilder builder, String variables) {
        if (variables == null || variables.isBlank()) return;
        for (String variable : variables.split("[\\r\\n;]+")) {
            int separator = variable.indexOf('=');
            if (separator > 0) {
                builder.environment().put(variable.substring(0, separator).trim(),
                        variable.substring(separator + 1).trim());
            }
        }
    }

    private static void runProcess(ProcessBuilder builder, String operation, Consumer<String> log)
            throws IOException {
        Process process = builder.start();
        try (BufferedReader output = new BufferedReader(new InputStreamReader(
                process.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = output.readLine()) != null) log.accept(line);
        }
        try {
            int exitCode = process.waitFor();
            if (exitCode != 0) throw new IOException(operation + " failed with exit code " + exitCode);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IOException(operation + " interrupted", e);
        }
    }

    private static void unzip(byte[] zipBytes, Path target) throws IOException {
        Path root = target.toAbsolutePath().normalize();
        try (ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(zipBytes))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                Path out = root.resolve(entry.getName()).normalize();
                if (!out.startsWith(root)) {
                    throw new IOException("Blocked zip entry outside target: " + entry.getName());
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(out);
                } else {
                    Files.createDirectories(out.getParent());
                    Files.copy(zis, out);
                }
                zis.closeEntry();
            }
        }
    }

    // ------------------------------------------------------------------ git

    private static void initGit(Path dir, Consumer<String> log) {
        try {
            Process p = new ProcessBuilder("git", "init")
                    .directory(dir.toFile())
                    .redirectErrorStream(true)
                    .start();
            p.getInputStream().readAllBytes();
            int code = p.waitFor();
            log.accept(code == 0 ? "Initialized git repository"
                    : "git init exited with code " + code);
        } catch (IOException e) {
            log.accept("git not found on PATH \u2014 skipped repository init");
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    // -------------------------------------------------------------- helpers

    private static String enc(String s) {
        return URLEncoder.encode(s == null ? "" : s, StandardCharsets.UTF_8);
    }

    private static String required(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private static String shorten(String s) {
        return s.length() > 400 ? s.substring(0, 400) + "\u2026" : s;
    }
}