package dev.lumina.tools;

import java.util.Objects;

/**
 * Model representing an Auto-Approve rule for file edits generated by GitHub Copilot chat in Lumina IDE.
 */
public class FileEditAutoApproveRule implements Cloneable {

    private String pattern = "";
    private String description = "";
    private String type = "Custom"; // "Default" or "Custom"
    private boolean autoApprove = false; // false = Never, true = Always

    public FileEditAutoApproveRule() {
    }

    public FileEditAutoApproveRule(String pattern, String description, String type, boolean autoApprove) {
        this.pattern = pattern != null ? pattern : "";
        this.description = description != null ? description : "";
        this.type = type != null ? type : "Custom";
        this.autoApprove = autoApprove;
    }

    public String getPattern() {
        return pattern;
    }

    public void setPattern(String pattern) {
        this.pattern = pattern != null ? pattern : "";
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description != null ? description : "";
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type != null ? type : "Custom";
    }

    public boolean isAutoApprove() {
        return autoApprove;
    }

    public void setAutoApprove(boolean autoApprove) {
        this.autoApprove = autoApprove;
    }

    @Override
    public FileEditAutoApproveRule clone() {
        try {
            return (FileEditAutoApproveRule) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FileEditAutoApproveRule that = (FileEditAutoApproveRule) o;
        return autoApprove == that.autoApprove &&
                Objects.equals(pattern, that.pattern) &&
                Objects.equals(description, that.description) &&
                Objects.equals(type, that.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pattern, description, type, autoApprove);
    }

    @Override
    public String toString() {
        return "FileEditAutoApproveRule{" +
                "pattern='" + pattern + '\'' +
                ", description='" + description + '\'' +
                ", type='" + type + '\'' +
                ", autoApprove=" + autoApprove +
                '}';
    }
}
